import { Link } from 'react-router-dom';
import { AirVent, ArrowRight, ArrowUpRight, Building2, Check, Factory, GraduationCap, HeartPulse, ShieldCheck, Sparkles, Wind } from 'lucide-react';

const solutions = [
  ['Workplaces', 'Keep teams focused with continuously cleaner indoor air.', Building2, 'from-[#e7f3e5] to-[#b7d8ba]'],
  ['Education', 'Create healthier classrooms for learning and growth.', GraduationCap, 'from-[#e8f0fb] to-[#b8cce8]'],
  ['Healthcare', 'Support sensitive spaces with intelligent purification.', HeartPulse, 'from-[#f9e8e5] to-[#edc5bc]'],
  ['Industry', 'Protect people where the air has to work harder.', Factory, 'from-[#f4eedf] to-[#ddcda6]'],
];

const Home = () => (
  <main className="overflow-hidden bg-[#f8faf6] text-[#163125]">
    <section className="relative isolate overflow-hidden bg-[#edf5e9] pt-36 sm:pt-44">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_72%_28%,rgba(151,205,160,.48),transparent_25%),radial-gradient(circle_at_87%_74%,rgba(215,238,204,.9),transparent_28%)]" />
      <div className="max-w-7xl mx-auto grid items-center gap-12 px-6 pb-20 sm:px-10 lg:grid-cols-2 lg:gap-8 lg:pb-28">
        <div className="max-w-2xl">
          <p className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#2d6942]/15 bg-white/70 px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#2d6942]"><Sparkles className="h-3.5 w-3.5" /> Clean air for everyday life</p>
          <h1 className="font-['Geist'] text-5xl font-light leading-[.94] tracking-tight sm:text-7xl lg:text-[5.3rem]">Breathe easier. <em className="font-['Instrument_Serif'] font-normal">Live better.</em></h1>
          <p className="mt-7 max-w-xl text-lg leading-relaxed text-[#163125]/70 sm:text-xl">EcoBreathe air purifiers quietly remove dust, pollen, smoke and everyday pollutants—so your home feels as fresh as it should.</p>
          <div className="mt-9 flex flex-wrap gap-4"><Link to="/shop" className="inline-flex items-center gap-2 rounded-full bg-[#1e5936] px-6 py-3.5 font-medium text-white shadow-xl shadow-[#1e5936]/20 transition hover:-translate-y-0.5 hover:bg-[#17492c] hover:no-underline">Shop air purifiers <ArrowRight className="h-4 w-4" /></Link><a href="#how-it-works" className="rounded-full px-4 py-3 text-sm font-medium text-[#1e5936] hover:bg-white/70 hover:no-underline">How it works</a></div>
          <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-medium text-[#27583a]"><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-[#3d9c56]" /> HEPA-grade filtration</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-[#3d9c56]" /> Whisper-quiet sleep mode</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-xl lg:translate-x-8"><div className="absolute inset-x-[10%] bottom-6 h-14 rounded-[50%] bg-[#2b6a40]/20 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/80 bg-white/60 p-5 shadow-2xl shadow-[#1e5936]/15 sm:p-8"><img src="/air-purifier-hero.png" alt="EcoBreathe air purifier in a bright home" className="h-[380px] w-full object-cover object-center sm:h-[480px]" /><div className="absolute bottom-10 left-10 rounded-2xl border border-white/70 bg-white/90 px-4 py-3 shadow-lg backdrop-blur"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#1e5936]/60">Indoor air quality</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold"><span className="h-2 w-2 rounded-full bg-[#48ae62]" /> Clean & protected</p></div></div></div>
      </div>
    </section>
    <section className="border-y border-[#163125]/8 bg-white py-7"><div className="max-w-7xl mx-auto flex flex-wrap items-center justify-center gap-x-10 gap-y-3 px-6 text-sm font-medium text-[#163125]/55 sm:justify-between sm:px-10"><span>Captures 99.97% of fine particles*</span><span>Designed for rooms up to 650 sq ft</span><span>Free delivery & 30-day returns</span></div></section>
    <section id="how-it-works" className="py-24 sm:py-32"><div className="max-w-7xl mx-auto px-6 sm:px-10"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#2d7b46]">Made for the air you live in</p><h2 className="mt-5 font-['Geist'] text-4xl font-light leading-tight tracking-tight sm:text-6xl">A cleaner room begins with a smarter <em className="font-['Instrument_Serif'] font-normal">system.</em></h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[['01', 'Sense', 'Integrated sensors respond to the air in your room, not a preset timer.', Wind], ['02', 'Purify', 'A multi-stage filter traps particles, allergens and unwanted odors.', AirVent], ['03', 'Protect', 'See your air improve in real time and breathe with confidence.', ShieldCheck]].map(([number, title, copy, Icon]) => <article key={title} className="rounded-3xl border border-[#163125]/8 bg-white p-7 shadow-sm"><span className="text-sm font-semibold text-[#54a86a]">{number}</span><Icon className="mt-12 h-8 w-8 text-[#1e5936]" /><h3 className="mt-5 font-['Geist'] text-2xl font-medium">{title}</h3><p className="mt-3 leading-relaxed text-[#163125]/60">{copy}</p></article>)}</div></div></section>
    <section className="bg-[#173d29] py-20 text-white sm:py-28"><div className="max-w-7xl mx-auto grid items-center gap-12 px-6 sm:px-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#91d4a0]">Meet EcoBreathe Pro</p><h2 className="mt-5 max-w-xl font-['Geist'] text-4xl font-light leading-tight tracking-tight sm:text-6xl">Powerful purification. Beautifully quiet.</h2><p className="mt-6 max-w-lg text-lg leading-relaxed text-white/65">A premium purifier that adapts automatically as your indoor air changes—while blending into the spaces you love.</p><Link to="/shop" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-medium text-[#173d29] transition hover:-translate-y-0.5 hover:no-underline">Explore the Pro <ArrowUpRight className="h-4 w-4" /></Link></div><div className="overflow-hidden rounded-[2rem] bg-[#d8ead1] p-4 shadow-2xl shadow-black/20"><img src="/air-purifier-hero.png" alt="EcoBreathe Pro air purifier" className="h-[300px] w-full rounded-[1.3rem] object-cover object-center sm:h-[380px]" /></div></div></section>
    <section className="py-24 sm:py-32"><div className="max-w-7xl mx-auto px-6 sm:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#2d7b46]">For organizations</p><h2 className="mt-5 font-['Geist'] text-4xl font-light tracking-tight sm:text-6xl">Better air, wherever work happens.</h2></div><Link to="/shop" className="inline-flex items-center gap-2 font-medium text-[#1e5936] hover:no-underline">Find your solution <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{solutions.map(([title, description, Icon, tone]) => <article key={title} className={`group min-h-72 rounded-3xl bg-gradient-to-br ${tone} p-6 transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-[#163125]/10`}><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/70 text-[#1e5936]"><Icon className="h-6 w-6" /></div><div className="mt-24"><h3 className="font-['Geist'] text-2xl font-medium">{title}</h3><p className="mt-3 leading-relaxed text-[#163125]/65">{description}</p></div></article>)}</div></div></section>
    <section className="px-6 pb-24 sm:px-10 sm:pb-32"><div className="max-w-7xl mx-auto overflow-hidden rounded-[2rem] bg-[#dcefd6] px-7 py-14 text-center sm:px-16 sm:py-20"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#2d7b46]">Make room for better air</p><h2 className="mx-auto mt-5 max-w-2xl font-['Geist'] text-4xl font-light tracking-tight sm:text-6xl">Your clean-air routine starts here.</h2><Link to="/shop" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#1e5936] px-6 py-3.5 font-medium text-white transition hover:bg-[#17492c] hover:no-underline">Shop EcoBreathe <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>
);

export default Home;